ARG REPO=mcr.microsoft.com/dotnet/core/runtime-deps
FROM $REPO:3.1-buster-slim

MAINTAINER Mike <ozczecho@yahoo.com>

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl locales \
    && rm -rf /var/lib/apt/lists/*

RUN sed -i -e 's/# en_AU.UTF-8 UTF-8/en_AU.UTF-8 UTF-8/' /etc/locale.gen && \
    locale-gen
ENV TZ=Australia/Sydney
ENV LANG en_AU.utf8
ENV LANGUAGE ${LANG}
ENV LC_ALL ${LANG}

RUN mkdir -p /dotnet/bin

COPY bin /dotnet
COPY bin/appsettings.json /appsettings.json


EXPOSE 5353

CMD ["./dotnet/VzduchDotek.Net"]